
# MQTT configuration
MQTT_PORT = "<YOUR_BROKER_ENDPOINT_PORT>"
MQTT_HOST = "<YOUR_BROKER_ENDPOINT>"
MQTT_QOS = 0
THING_ID = "<YOUR_THING_NAME>"
THING_CLIENT_CERT = "<YOUR_CERT_PREFIX>-certificate.pem.crt"
THING_PRIVATE_KEY = "<YOUR_CERT_PREFIX>-private.pem.key"
THING_ROOT_CA=""
